### PR TITLE
Update tutorials.rst

### LINKED ISSUE #99: can kivmob work with api 29?
it is working on api 27, but when i changed my app into api 29 it doesn't work.
Screenshot_17
it's a screenshot from the logcat

### PR DESCRIPTION
**Pull request by nekoprog**
Latest version of SDK, NDK and firebase-ads that's working.

Will eliminate errors such as
```
Execution failed for task ':checkDebugAarMetadata'.
```
and
```
android:exported needs to be explicitly specified for element <receiver#com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver>
```

Will close #99, #118, #122 and #123

### CODE REVIEW

**Comment by nekoprog** [comment]
Will probably close these issues #99 #118 #122

**Comment by nekoprog** [comment]
Ads not showing, got errors
```
01-28 23:46:03.580 10547 10663 I python  : [INFO   ] [KivMob      ] __init__ called.
01-28 23:46:03.580 10547 10663 I python  : [INFO   ] [KivMob      ] Android platform detected.
01-28 23:46:03.584 10547 10663 I python  : [INFO   ] [KivMob      ] new_banner() called.
01-28 23:46:03.585 10547 10547 I python  :  Traceback (most recent call last):
01-28 23:46:03.585 10547 10663 I python  : [INFO   ] [KivMob      ] request_banner() called.
01-28 23:46:03.586 10547 10547 I python  :    File "/home/test/testmob/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/testmob/arm64-v8a/android/runnable.py", line 38, in run
01-28 23:46:03.586 10547 10663 I python  : [INFO   ] [KivMob      ] show_banner() called.
01-28 23:46:03.590 10547 10547 I python  :    File "/home/test/testmob/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/testmob/arm64-v8a/kivmob.py", line 188, in __init__
01-28 23:46:03.590 10547 10547 I python  :  NameError: name 'MobileAds' is not defined
01-28 23:46:03.602 10547 10547 I python  :  Traceback (most recent call last):
01-28 23:46:03.602 10547 10547 I python  :    File "/home/test/testmob/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/testmob/arm64-v8a/android/runnable.py", line 38, in run
01-28 23:46:03.603 10547 10547 I python  :    File "/home/test/testmob/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/testmob/arm64-v8a/kivmob.py", line 204, in new_banner
01-28 23:46:03.603 10547 10663 I python  : [WARNING] [Base        ] Unknown <android> provider
01-28 23:46:03.603 10547 10547 I python  :  NameError: name 'View' is not defined
01-28 23:46:03.604 10547 10663 I python  : [INFO   ] [Base        ] Start application main loop
01-28 23:46:03.609 10547 10663 I python  : [INFO   ] [GL          ] NPOT texture support is available
01-28 23:46:03.610 10547 10547 I python  :  Traceback (most recent call last):
01-28 23:46:03.610 10547 10547 I python  :    File "/home/test/testmob/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/testmob/arm64-v8a/android/runnable.py", line 38, in run
01-28 23:46:03.615 10547 10547 I python  :    File "/home/test/testmob/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/testmob/arm64-v8a/kivmob.py", line 221, in request_banner
01-28 23:46:03.615 10547 10547 I python  :    File "/home/test/testmob/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/testmob/arm64-v8a/kivmob.py", line 290, in _get_builder
01-28 23:46:03.616 10547 10547 I python  :  AttributeError: 'AndroidBridge' object has no attribute '_test_devices'
01-28 23:46:03.618 10547 10547 I python  :  Traceback (most recent call last):
01-28 23:46:03.619 10547 10547 I python  :    File "/home/test/testmob/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/testmob/arm64-v8a/android/runnable.py", line 38, in run
01-28 23:46:03.619 10547 10547 I python  :    File "/home/test/testmob/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/testmob/arm64-v8a/kivmob.py", line 225, in show_banner
01-28 23:46:03.619 10547 10547 I python  :  NameError: name 'View' is not defined
```

**Review by MichaelStott — APPROVED** [review]

**Comment by MichaelStott** [comment]
tyvm!

**Comment by nekoprog** [comment]
no problem. but how to pull git version from buildozer requirements? can you help? because pip version is too old and causing errors.

**Comment by diogokravetz** [comment]
Hello,  even after the changes the errors in gradle still remain, when compiling buildozer return :
[WARNING]: ERROR: /content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/kivmob/gradlew failed!

**Comment by diogokravetz** [comment]
What could be the problem?

**Comment by MichaelStott** [comment]
I can try taking a look in a little bit. Haven't been able to dedicate much time to this project as of late.

**Comment by nekoprog** [comment]
> Hello, even after the changes the errors in gradle still remain, when compiling buildozer return : [WARNING]: ERROR: /content/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/kivmob/gradlew failed!

can you open new issue with full log? i can help you debug it.

> I can try taking a look in a little bit. Haven't been able to dedicate much time to this project as of late.

thanks, probably they have updated the admob pointer in new firebase-ads
i want to help, but not very familiar with java and jython.

**Comment by diogokravetz** [comment]
@nekoprog yes the error is in build.gradle': 79: Unexpected input: '{'

**Comment by diogokravetz** [comment]
thanks for the help @nekoprog @MichaelStott , I'm also not very familiar with jnius, but I'll try to find a solution to be able to compile using the most current version of the admob SDK, because if I use android.gradle_dependencies='com.google.firebase:firebase-ads:15.0 .0' in my apps, the google play console return the error:
This SDK version has been reported as out of date. Upgrade to a newer one (19.2.0+).

**Comment by mecrayavcin** [comment]
> @nekoprog yes the error is in build.gradle': 79: Unexpected input: '{'

same

**Pull request merged**
